go-micro/plugins

v4/events/natsjs/nats.go

Using the topic means that the subscription will wrongly be reused on
subsequent, distinct subscriptions for the same topic.
/cc @wkloucek @xpunch

Use the queue group name as the durable subscription name

---

v4/store/memory/memory.go

When the memory implementation of the store.List() uses a prefix it will now only return the matching entries instead of matching entries mixed with emptystring for mismatches.

store: do not list emptystring for prefix mismatches

---

v4/broker/rabbitmq/connection.go
v4/broker/rabbitmq/rabbitmq.go

#https://github.com/asim/go-micro/pull/2492

fix: consume and publish blocked after rabbitmq reconnecting

---

v2/registry/consul/watcher.go
v3/registry/consul/watcher.go
v4/registry/consul/watcher.go

before: go-micro service will watch all catalog in consul , it will put a lot of burden on Consul
after: go-micro service only watch that the called service in Consul ,

feat: optimization consul watcher

---

v4/store/redis/redis.go

Because Init and New method will call configure, May cause duplicate Client resources to be declared and not released

fixed if configure repeat, client resource close

---

v4/events/redis/options.go
v4/events/redis/redis.go

Allows the user to pass client options (eg. `?dial_timeout=3`)
It aligns the behavior with other redis plugins (cache, store, broker)
The previous format is still accepted

feat(events/redis): Allow redis:// address in events

---

v4/wrapper/service/service.go

Add a matching option provided for clients/handlers to add the service into the context for subscribers, to allow subscription handlers to access the service and configured components.

feat(wrapper/service): Add subscriber wrapper

---

v4/broker/rabbitmq/rabbitmq.go

As the way credentials are passed to RabbitMQ is through the address, this ensures that `Address()` returns a redacted URL to prevent username/password from being shown in logs.
Closes #42

feat(broker/rabbitmq): Redact creds in Address()

---

v4/registry/consul/consul.go

Assign node.Metadata to consul agent's Meta when registering services.

list metadata value in consul's meta page

---

v4/broker/rabbitmq/rabbitmq.go

Closing the RabbitMQ channel upon unsubscribe prevents any in-flight messages from sending an ack/nack if autoack is disabled.
This change instead waits for the subscription to exit if autoack is disabled to allow any in-flight handlers to complete, thus marking the message appropriately.

fix(broker/rabbitmq): Wait for handler upon unsub if autoack disabled

---

v4/broker/rabbitmq/rabbitmq.go

RabbitMQ allows various types of values in message headers, such as string, int, float, time, etc.
Currently, if a RabbitMQ header value in a message is not a string, then the conversion to the go-micro `map[string]string`  based headers results in `""` being set for non-string values, due to direct casting.
This change instead attempts to convert the value via `fmt.Sprintf` instead, which should allow at least basic (non-nested) types to be set correctly, such as `x-delivery-count` set by [quorum queues for poison message handling](https://www.rabbitmq.com/quorum-queues.html#poison-message-handling).

fix(broker/rabbitmq): header conversion for non-string types

---

v4/sync/etcd/etcd.go

The call to `NewSession()` when creating a lock triggers a continuous keep-alive go routine that will remain running until the session is explicitly closed.
So, if `Lock()` and `Unlock()` are called repeatedly, this results in a leak of both go routines on the service-side and leases on the etcd-side, until the service is restarted.
This change closes the underlying session if the lock is successfully closed, to prevent said leak. Similar change might need to be made on the `Leader()` and `Resign()` functions.

fix(sync/etcd): close lock session to prevent lease leak

---

v4/server/http/http.go

Unlike grpc server, the http server does not passthrough the given subscriber context to the broker, which means certain broker plug-in specific configuration options could be missed when subscribing.
This change fixes the behavior to be consistent with grpc server.

fix(server/http): passthrough subscriber ctx

---

v4/cache/redis/options.go
v4/cache/redis/options_test.go
v4/cache/redis/redis.go
v4/events/redis/options.go
v4/events/redis/options_test.go
v4/events/redis/redis.go
v4/store/redis/options.go
v4/store/redis/redis.go
v4/store/redis/redis_test.go

Add `WithRedisOptions` option that accept a `redis.UniversalOptions` struct :
1. If the MasterName option is specified, a sentinel-backed FailoverClient is returned.
2. if the number of Addrs is two or more, a ClusterClient is returned.
3. Otherwise, a single-node Client is returned.

feat(cache;store;events/redis): Add cluster and sentinel failover support

---

v3/server/grpc/grpc.go

I just found out that graceful shutdown is not working in grpc server plugin.
I expect server.Wait option to create internal wg to wait for all requests to be handled when kubernetes terminates pods.
But WaitGroup is only initiated in constructor and there's no way to reconfigure it.
This is how I turn on graceful shutdown:
```golang
service := micro.NewService(
micro.Name("greeter"),
)
service.Init()
var wg sync.WaitGroup
srv := service.Server()
if err := srv.Init(server.Wait(&wg)); err != nil {
log.Fatal("failed to init micro server", zap.Error(err))
}
```

server/grpc: initiate wg on configure call instead of constructor

---

v4/config/source/nats/options.go

fix(config/source/nats): urlKey{} option assuming multiple urls, but method nats.WithUrl put single url in context. Added wrapped array for method WithUrl , add new method WithUrls for multiple urls.

Error while try get configure from remote nats. 

---

v4/client/grpc/grpc.go

The HTTP/2 spec consider the request malformed
This header may have been added from a WebSocket connection

fix(client/grpc): Removes the `connection` header

---

v4/logger/zap/options.go
v4/logger/zap/zap.go
v4/logger/zap/zap_test.go

In my use case, I already has a `zap.logger` instance, and I want to reuse it in go-micro logger. So I add an option to use the `zap.Logger` directly.

feat(logger/zap): direct use of zap.Logger

---

v4/store/redis/redis.go

This PR reintroduces mapping the `redis.Nil` error to `store.ErrNotFound`

handle redis.Nil error properly

---

v4/store/redis/redis.go

The plugin stores the keys prefixed with the "Table" name in Redis. We should remove that prefix from the keys returned by "List()".
Partial-Fix: #57

redis: Fix List call to strip table prefix from result

---

v4/registry/kubernetes/client/watch/body.go

Under heavy request load we encounter this panic:
```
panic: send on closed channel
goroutine 44488 [running]:
github.com/go-micro/plugins/v4/registry/kubernetes/client/watch.(*bodyWatcher).stream.func2()
github.com/go-micro/plugins/v4/registry/kubernetes@v1.1.1/client/watch/body.go:72 +0x1ab
created by github.com/go-micro/plugins/v4/registry/kubernetes/client/watch.(*bodyWatcher).stream
github.com/go-micro/plugins/v4/registry/kubernetes@v1.1.1/client/watch/body.go:51 +0x23b
```
With this PR we no longer see this panic.
AFAICT this is caused by closign the channel at the wrong time. Channels are rather unmapped territory for me, so let me know if this is the proper solution.

kubernetes registry: do not send to closed channel

---

v4/registry/kubernetes/watcher.go

with https://github.com/go-micro/plugins/pull/113 we sometines see a panic like this:
```
panic: close of closed channel
goroutine 21629 [running]:
github.com/go-micro/plugins/v4/registry/kubernetes.(*k8sWatcher).Stop(0xc003e2f880)
github.com/go-micro/plugins/v4/registry/kubernetes@v1.1.1/watcher.go:167 +0x56
go-micro.dev/v4/registry/cache.(*cache).watch.func1()
go-micro.dev/v4@v4.9.0/registry/cache/cache.go:409 +0xe9
created by go-micro.dev/v4/registry/cache.(*cache).watch
go-micro.dev/v4@v4.9.0/registry/cache/cache.go:403 +0xb8
```
I'm not proud of this solution and I tried using a Context and ContextCancel function as in the bodyWatcher, but that caused more problems than it solved. Any pointers on how to tackle this properly are welcome.

only close channel once

---

v4/events/natsjs/nats.go
v4/events/natsjs/options.go

We ran into problems when the nats server is crashing. Clients would keep the events in their queue waiting for nats to come up again. (This is the point in async publishing.) However if the clients get restarted while nats is gone the events will be lost and there is no way to retrieve them. 
This adds a configuration option to do synchronous publishes instead. The default is still asynchronous so there are no breaking changes.

Allow synchronous publishing in Nats

---

v4/registry/nats/nats.go
v4/registry/nats/options.go

We are using nats as service registry. When a service is restarting it wouldn't update the registry entry. Looking into it, this was because the nats registry only does a `"create"` action when storing to nats. That means that existing entries are not overwritten.
Since it looked like it was a deliberate decision to use `"create"`, this adds a configuration option `RegisterAction` for it. It can be used with `"put"` to update *or* create a new registry entry. It could also be used with `"update"` if one doesn't want to create new registry entries if they do not exist.
The default is still `"create"` so there are no breaking changes.

Nats registry action

---

v4/events/natsjs/nats.go
v4/events/natsjs/options.go

Allow to set names for the nats connections. In big deployments it can be cumbersome to keep track of nats connections otherwise

Allow naming nats connections

---

v4/broker/rabbitmq/options.go

`Event.Publish` accept client.PublishOption, so I add a new  client.PublishOption to set message delivery mode.
It has the same functionality with `rabbitmq.DeliveryMode()`, but as a `client.PublishOption`
```go
// Event is used to publish messages to a topic.
type Event interface {
// Publish publishes a message to the event topic
Publish(ctx context.Context, msg interface{}, opts ...client.PublishOption) error
}
```
usage:
```go
...
publisher := micro.NewEvent(topic, microClient).
opt := rabbitmq.PublishDeliveryMode(2)
publisher.Publish(ctx, msg, opt)
...
```

feat: add rabbitmq.PublishDeliveryMode, a client.PublishOption for setting message delivery mode

---

v4/events/natsjs/nats.go
v4/events/natsjs/options.go

Adds an option to authenticate via username/password to the `events/natsjs` implementation

Allow username/password authentication in events/natsjs
